name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # todos os dias à meia-noite
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate GitHub Snake
        uses: Platane/snk@v3
        with:
          github_user_name: rafaolivio
          outputs: |
            ./output/snake.svg

      - name: Push generated SVG
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "generate snake"
          add: "./output/snake.svg"
